name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / bicep (github-check)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: ./
        with:
          workdir: ./testdata/

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / bicep (github-pr-check)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: ./
        with:
          workdir: ./testdata/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / bicep (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          workdir: ./testdata/
